repos:
- repo: local
  hooks:
    - id: ruff-check
      name: ruff check
      entry: uv run ruff check
      language: system
      pass_filenames: false
    - id: ruff-format
      name: ruff format
      entry: uv run ruff format
      language: system
      pass_filenames: false
    - id: mypy
      name: mypy
      entry: uv run mypy --strict .
      language: system
      pass_filenames: false
# - repo: https://github.com/astral-sh/ruff-pre-commit
#   rev: v0.15.13
#   hooks:
#     # Run the linter
#     - id: ruff-check
#       args: [ --fix ]
#     # Run the formatter
#     - id: ruff-format
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
    - id: check-yaml
    - id: trailing-whitespace

