"""
shapefile.py
Provides read and write support for ESRI Shapefiles.
authors: jlawhead<at>geospatialpython.com
maintainer: karim.bahgat.norway<at>gmail.com
Compatible with Python versions >=3.9
"""

from __future__ import annotations

import logging

from .__main__ import main
from .__version__ import __version__
from .classes import Field, ShapeRecord, ShapeRecords, Shapes
from .constants import (
    FIRST_RING,
    INNER_RING,
    MISSING,
    MULTIPATCH,
    MULTIPOINT,
    MULTIPOINTM,
    MULTIPOINTZ,
    NODATA,
    NULL,
    OUTER_RING,
    PARTTYPE_LOOKUP,
    POINT,
    POINTM,
    POINTZ,
    POLYGON,
    POLYGONM,
    POLYGONZ,
    POLYLINE,
    POLYLINEM,
    POLYLINEZ,
    REPLACE_REMOTE_URLS_WITH_LOCALHOST,
    RING,
    SHAPETYPE_LOOKUP,
    SHAPETYPENUM_LOOKUP,
    TRIANGLE_FAN,
    TRIANGLE_STRIP,
)
from ._doctest_runner import _replace_remote_url
from .exceptions import GeoJSON_Error, RingSamplingError, ShapefileException
from .geometric_calculations import bbox_overlap
from .helpers import _Array, fsdecode_if_pathlike
from .reader import Reader
from .shapes import (
    SHAPE_CLASS_FROM_SHAPETYPE,
    MultiPatch,
    MultiPoint,
    MultiPointM,
    MultiPointZ,
    NullShape,
    Point,
    PointM,
    PointM_shapeTypes,
    PointZ,
    PointZ_shapeTypes,
    Polygon,
    PolygonM,
    PolygonZ,
    Polyline,
    PolylineM,
    PolylineZ,
    Shape,
    _CanHaveBBox_shapeTypes,
    _HasM,
    _HasM_shapeTypes,
    _HasZ,
    _HasZ_shapeTypes,
)
from .types import (
    FIELD_TYPE_ALIASES,
    BBox,
    BinaryFileStreamT,
    BinaryFileT,
    Coord,
    Coords,
    FieldType,
    FieldTypeT,
    MBox,
    Point2D,
    Point3D,
    PointMT,
    PointsT,
    PointT,
    PointZT,
    ReadableBinStream,
    ReadSeekableBinStream,
    ReadWriteSeekableBinStream,
    RecordValue,
    RecordValueNotDate,
    WriteableBinStream,
    WriteSeekableBinStream,
    ZBox,
)
from .writer import Writer

__all__ = [
    "__version__",
    "NULL",
    "POINT",
    "POLYLINE",
    "POLYGON",
    "MULTIPOINT",
    "POINTZ",
    "POLYLINEZ",
    "POLYGONZ",
    "MULTIPOINTZ",
    "POINTM",
    "POLYLINEM",
    "POLYGONM",
    "MULTIPOINTM",
    "MULTIPATCH",
    "SHAPETYPE_LOOKUP",
    "REPLACE_REMOTE_URLS_WITH_LOCALHOST",
    "SHAPETYPENUM_LOOKUP",
    "TRIANGLE_STRIP",
    "TRIANGLE_FAN",
    "OUTER_RING",
    "INNER_RING",
    "FIRST_RING",
    "RING",
    "PARTTYPE_LOOKUP",
    "MISSING",
    "NODATA",
    "Reader",
    "Writer",
    "fsdecode_if_pathlike",
    "_Array",
    "Shape",
    "NullShape",
    "Point",
    "Polyline",
    "Polygon",
    "MultiPoint",
    "MultiPointM",
    "MultiPointZ",
    "PolygonM",
    "PolygonZ",
    "PolylineM",
    "PolylineZ",
    "MultiPatch",
    "PointM",
    "PointZ",
    "SHAPE_CLASS_FROM_SHAPETYPE",
    "PointM_shapeTypes",
    "PointZ_shapeTypes",
    "_CanHaveBBox_shapeTypes",
    "_HasM",
    "_HasM_shapeTypes",
    "_HasZ",
    "_HasZ_shapeTypes",
    "Point2D",
    "Point3D",
    "PointMT",
    "PointZT",
    "Coord",
    "Coords",
    "PointT",
    "PointsT",
    "BBox",
    "MBox",
    "ZBox",
    "WriteableBinStream",
    "ReadableBinStream",
    "WriteSeekableBinStream",
    "ReadSeekableBinStream",
    "ReadWriteSeekableBinStream",
    "BinaryFileT",
    "BinaryFileStreamT",
    "FieldTypeT",
    "FieldType",
    "FIELD_TYPE_ALIASES",
    "RecordValueNotDate",
    "RecordValue",
    "ShapefileException",
    "RingSamplingError",
    "GeoJSON_Error",
    "Field",
    "Shapes",
    "ShapeRecord",
    "ShapeRecords",
    "bbox_overlap",
    "main",
    "_replace_remote_url",
]

logger = logging.getLogger(__name__)
