name: Unexpected Behavior
description: You think PyShp might be doing something wrong.
title: "Title goes here..."
labels: ["bug"]
body:
  - type: input
    id: pyshp-version
    attributes:
      label: PyShp Version
      description: Please input the version of PyShp you used. If unsure, call `shapefile.__version__`. 
      placeholder: ...
    validations:
      required: true
  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: Please input the version of the Python executable. 
      placeholder: ...
    validations:
      required: true
  - type: textarea
    id: your-code
    attributes:
      label: Your code
      description: Please copy-paste the relevant parts of your code or script that you tried to run. 
      placeholder: ...
      render: shell
    validations:
      required: true
  - type: textarea
    id: expected-results
    attributes:
      label: Expected results
      description: Please describe what you expected to see in the output.
      placeholder: ...
    validations:
      required: true
  - type: textarea
    id: actual-results
    attributes:
      label: Actual results
      description: Please describe what you actually saw in the output.
      placeholder: ...
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: Other notes
      description: Please input any other notes that may be relevant, e.g. do you have any thoughts on what might be wrong? 
      placeholder: ...
    validations:
      required: false