name: "Close PRs that didn't run workflows, or mention no issue"

on:
  pull_request_target:
    types: [opened, reopened]
    branches:
      - master

jobs:
  verify:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - uses: NotTodayThankyou/NotTodayThankyou@v1
        with:
          post-comment: "false"
