# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: build

on:
  push:
    branches: [ PyShp-CI-test-on-Python-3.10+ ]
  pull_request:
    branches: [ PyShp-CI-test-on-Python-3.10+ ]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        python-version: ["2.7.18", "3.5.10", "3.6.15", "3.7.17", "3.8.18", "3.9.18",  "3.10.13", "3.11.7", "3.12.1", "3.13.0a2"]

    runs-on: ubuntu-latest
    container:
      image: python:${{ matrix.python-version }}-slim

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
        if [ -f requirements.test.txt ]; then pip install -r requirements.test.txt; fi
    - name: Test with doctest
      run: |
        python shapefile.py
    - name: Test with pytest
      run: |
        pytest
