# This workflow will run the pre-commit hooks (including linters), and the tests with a variety of Python versions

name: build

on:
  push:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
    - uses: pre-commit/action@v3.0.1

  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: [
            "2.7",
            "3.5",
            "3.6",
            "3.7",
            "3.8",
            "3.9",
            "3.10",
            "3.11",
            "3.12",
            "3.13.0a2",
        ]
        os: [
          "ubuntu-latest",
        ]
        include:
          - os: "windows-latest"
            python-version: "3.13"
          - os: "macos-latest"
            python-version: "3.13"

    runs-on: matrix.os
    steps:
    - uses: actions/checkout@v4

    - name: Run tests
      uses: ./.github/actions/test
      with:
        python_version: ${{ matrix.python_version }}
