# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: deploy

on:
  release:
    types: [published]

jobs:
  format_type_check_lint_build_and_test:
    # Builds and uploads wheel and sdist
    uses: ./.github/workflows/run_checks_build_and_test.yml

  deploy:
    # Prevent deployment of releases that fail any tests or checks (e.g. linting).
    needs: format_type_check_lint_build_and_test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'


    - name: Download wheel and sdist (built in previous job)
      uses: actions/download-artifact@v4
      with:
        name: PyShp_wheel_and_sdist
        path: dist



    - name: Publish package
      if: github.repository == 'GeospatialPython/pyshp'
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_INTEGRATION }}
        packages-dir: dist/
