# This workflow will run the pre-commit hooks (including linters), and the tests with a variety of Python versions

name: Run pre-commit hooks and tests

on:
  push:
  pull_request:
    branches: [ master ]
  workflow_call:
  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
    - uses: pre-commit/action@v3.0.1

  test_in_slim_Python_containers:
    strategy:
      fail-fast: false
      matrix:
        python-version: [
            "2.7",
            "3.5",
            "3.6",
            "3.7",
            "3.8",
            "3.9",
            "3.10",
            "3.11",
            "3.12",
            "3.13.0a2",
        ]

    runs-on: ubuntu-latest
    container:
      image: python:${{ matrix.python-version }}-slim

    steps:
    - uses: actions/checkout@v4

    - name: Run tests
      uses: ./.github/actions/test


  test_on_MacOS_and_Windows:
    if: github.repository == 'GeospatialPython/pyshp'
    strategy:
      fail-fast: false
      matrix:
        python-version: [
          "3.12",
        ]
        os: [
          # "macos-12",
          "ubuntu-24.04",
          "windows-2022",
        ]
        # include:
        #   - os: "windows-latest"
        #     python-version: "3.13"
        #   - os: "macos-latest"
        #     python-version: "3.13"

    runs-on: matrix.os
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python_version }}

    - name: Run tests
      uses: ./.github/actions/test
